# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-01 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickevent',
            name='kirr_url',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shortener.KirrURL'),
        ),
    ]
