# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirrurl',
            name='shortcode',
            field=models.CharField(default='defolturlshortcode', max_length=15),
            preserve_default=False, # не будет присваиваться всем созданным без значения
            # элементам shortener
        ),
    ]
