# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-24 19:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20161220_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirrurl',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='kirrurl',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 12, 24, 19, 39, 13, 500723, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
