# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20161225_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kirrurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
    ]
